version: "3.6"

services:
  db:
    build:
      context: application/db/
      dockerfile: Dockerfile.db.compose
    container_name: jdbc-mysql
    ports:
      - 3306:3306
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=restdemo
      - DATABASE_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbt_demo
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  srv:
    build:
      context: application/
      dockerfile: Dockerfile.srv.compose
    container_name: spring-server
    depends_on:
      - db
    ports:
      - 8080:8080
